# Scripts to load and augment image batches

import os
import glob
import cv2
import torch
from torch.utils.data import Dataset, DataLoader

class RetinalDeblurDataset(Dataset):
    def __init__(self, raw_dir, processed_dir):
        """
        Dataset to load paired ground-truth (clean) and synthetic input (blurry) images.
        """
        self.raw_dir = raw_dir
        self.processed_dir = processed_dir
        
        # Gather all synthetically blurred image paths generated by simulator.py
        self.blurry_paths = sorted(glob.glob(os.path.join(processed_dir, '*.jpg')))
        
    def __len__(self):
        return len(self.blurry_paths)
        
    def __getitem__(self, idx):
        # 1. Load the blurry/noisy input image (y)
        blurry_path = self.blurry_paths[idx]
        blurry_img = cv2.imread(blurry_path, cv2.IMREAD_GRAYSCALE)
        
        # 2. Reconstruct corresponding ground truth filename (x)
        # Assumes simulator.py named them 'blurry_ORIGINALNAME.jpg'
        filename = os.path.basename(blurry_path).replace('blurry_', '')
        
        # Locate the clean matching ground truth file recursively in your raw directory
        raw_search = glob.glob(os.path.join(self.raw_dir, f'**/{filename}'), recursive=True)
        
        if not raw_search:
            raise FileNotFoundError(f"Could not find matching clean image for: {filename}")
            
        clean_img = cv2.imread(raw_search[0], cv2.IMREAD_GRAYSCALE)
        
        gaussian_blur = cv2.GaussianBlur(clean_img, (5,5), 1.0)
        clean_sharpened = cv2.addWeighted(clean_img, 1.5, gaussian_blur, -0.5, 0)
        
        # 3. Normalize values to 0.0 - 1.0 and convert arrays to PyTorch Tensors [C, H, W]
        blurry_tensor = torch.tensor(blurry_img, dtype=torch.float32).unsqueeze(0) / 255.0
        clean_tensor = torch.tensor(clean_img, dtype=torch.float32).unsqueeze(0) / 255.0
        
        return blurry_tensor, clean_tensor

def get_deblur_dataloader(raw_dir, processed_dir, batch_size=4, shuffle=True):
    """
    Returns a PyTorch DataLoader object for the training pipeline loop.
    """
    dataset = RetinalDeblurDataset(raw_dir, processed_dir)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, drop_last=True)

if __name__ == '__main__':
    # Test script execution to verify dataloader integration paths
    print("Testing data loader execution pipeline...")
    RAW_PATH = 'data/raw/extracted_images/augmented_resized_V2/train'
    PROCESSED_PATH = 'data/processed/train'
    
    try:
        loader = get_deblur_dataloader(RAW_PATH, PROCESSED_PATH, batch_size=2)
        blurry_batch, clean_batch = next(iter(loader))
        print(f"Pipeline verification success!")
        print(f"Blurry Batch Tensor Shape: {blurry_batch.shape}")  # Should be [2, 1, H, W]
        print(f"Clean Batch Tensor Shape: {clean_batch.shape}")    # Should be [2, 1, H, W]
    except Exception as e:
        print(f"Dataloader Test Failed: {e}")
